name: Beta Release
on:
  push:
    branches:
    - bugs

jobs:
  build:
    name: Beta Release
    if: github.repository == '4ooc/sdkman-cli'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Set git hash
      id: var 
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build artifacts
      run: ./gradlew -Penv=beta -Phash=${{ steps.var.outputs.sha_short }} clean assemble
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nobugs"
        title: "personal release"
        prerelease: true
        files: |
            build/distributions/*.*