name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./gradlew clean test --info
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Set github tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build artifacts
      run: ./gradlew -Penv=production -Prelease= ${{ steps.vars.outputs.tag }} -PbuildNumber=${{ steps.buildnumber.outputs.build_number }} clean assemble
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/distributions/sdkman-cli-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
